version: '3'
services:
  backend:
    build:
      args:
        user: www-data
        uid: 33
      context: .
    restart: always
    container_name: backend_om30
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: VSCODE
    extra_hosts:
      - 'postgres_om30:host-gateway'
      - 'redis_om30:host-gateway'
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./app/backend:/var/www
      - ./docker/php/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/backend.conf:/etc/nginx/conf.d/default.conf
      - ./app/frontend/dist/spa:/usr/share/nginx/html
    ports:
      - 80:80
      - 8000:8000
    networks:
      - netLocal
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./app/frontend
      target: develop
    restart: always
    container_name: frontend_om30
    ports:
      - '8080:8080'
    volumes:
      - './app/frontend:/app'
    networks:
      - netLocal
    depends_on:
      - backend
    command: /bin/sh -c "yarn && quasar dev"

  postgres:
    image: postgres:14.3-alpine
    restart: always
    container_name: postgres_om30
    networks:
      - netLocal
    volumes:
      - POSTGRES_VOLUME:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432

  redis:
    image: redis:7-alpine
    container_name: redis_om30
    restart: always
    networks:
      - netLocal
    ports:
      - 6379:6379

  adminer:
    image: adminer
    container_name: adminer_om30
    restart: always
    networks:
      - netLocal
    ports:
      - 8081:8080

volumes:
  POSTGRES_VOLUME:
    driver: local

networks:
  netLocal:
    driver: bridge
